In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("./datas/seoul.csv", encoding="cp949")
df1

,업소아이디,업소명,분류코드,분류코드명,업소 주소,업소 전화번호,추천수,상품명,상품가격(일반)(원)
0,9635,박연헤어,5,이 미용업,서울특별시 서울 도봉구 도봉로136길 111(창동),02-900-0838,0,커트,8000.0
1,9635,박연헤어,5,이 미용업,서울특별시 서울 도봉구 도봉로136길 111(창동),02-900-0838,0,파마,30000.0
2,9634,블루컷트,5,이 미용업,서울특별시 서울 도봉구 해등로 255(쌍문동),02-999-6922,0,염색,7000.0
3,9634,블루컷트,5,이 미용업,서울특별시 서울 도봉구 해등로 255(쌍문동),02-999-6922,0,커트,5000.0
4,9633,우이목장,1,한식,서울특별시 서울 도봉구 우이천로 298(쌍문동),02-904-3070,0,갈비탕,11000.0
...,...,...,...,...,...,...,...,...,...
2302,272,홍노래방,13,기타서비스업종,서울특별시 마포구 홍익로 1 (서교동),3142-1551,7,노래방이용료(3인),15000.0
2303,272,홍노래방,13,기타서비스업종,서울특별시 마포구 홍익로 1 (서교동),3142-1551,7,노래방이용료(2인),15000.0
2304,272,홍노래방,13,기타서비스업종,서울특별시 마포구 홍익로 1 (서교동),3142-1551,7,노래방이용료,15000.0
2305,263,장미미용실,5,이 미용업,서울특별시 서울 중랑구 용마산로129길 61-4,NaN,137,미용료(파마),20000.0
2306,263,장미미용실,5,이 미용업,서울특별시 서울 중랑구 용마산로129길 61-4,NaN,137,커트,10000.0

In [ ]:
df2 = df1[["업소명","분류코드","업소 주소","업소 전화번호"]]
df3=df2[df2["분류코드"]<=4].reset_index()

In [ ]:
df4 = df3[["업소명","업소 주소","업소 전화번호"]]

In [ ]:
df4

         업소명                            업소 주소           업소 전화번호
0       우이목장       서울특별시 서울 도봉구 우이천로 298(쌍문동)       02-904-3070
1     착한부대찌개  서울특별시 서울 도봉구 도봉로109길 46 2층(쌍문동)       02-902-0191
2     착한부대찌개  서울특별시 서울 도봉구 도봉로109길 46 2층(쌍문동)       02-902-0191
3        홍방원    서울특별시 서울 도봉구 도봉로169나길 47(도봉동)       02-954-0719
4        홍방원    서울특별시 서울 도봉구 도봉로169나길 47(도봉동)       02-954-0719
...      ...                              ...               ...
1638    감베로니        서울특별시 용산구 한강대로81길 5 (갈월동)  3273-1791
1639    감베로니        서울특별시 용산구 한강대로81길 5 (갈월동)  3273-1791
1640   장수설렁탕        서울특별시 송파구 백제고분로 148 (잠실동)  415-1472
1641   장수설렁탕        서울특별시 송파구 백제고분로 148 (잠실동)  415-1472
1642     무진장        서울특별시 용산구 원효로 212 (원효로2가)  712-8814

[1643 rows x 3 columns]

In [ ]:
df4.drop_duplicates(inplace = True)
df4.reset_index(inplace=True)
df5 = df4[["업소명","업소 주소","업소 전화번호"]]

C:\Users\Ji Hoon\AppData\Local\Temp\ipykernel_21868\3699669057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop_duplicates(inplace = True)

ValueError: cannot insert level_0, already exists

In [ ]:
df5 = df4[["업소명","업소 주소","업소 전화번호"]]
df5

         업소명                            업소 주소           업소 전화번호
0       우이목장       서울특별시 서울 도봉구 우이천로 298(쌍문동)       02-904-3070
1     착한부대찌개  서울특별시 서울 도봉구 도봉로109길 46 2층(쌍문동)       02-902-0191
2        홍방원    서울특별시 서울 도봉구 도봉로169나길 47(도봉동)       02-954-0719
3    오늘우리집비어    서울특별시 서울 중랑구 용마산로115길 109 지1층    0507-1469-0613
4      은평닭곰탕           서울특별시 은평구 연서로3길 5(역촌동)               NaN
..       ...                              ...               ...
727    원조막국수        서울특별시 강북구 노해로33길 49 (수유동)  991-5215
728     해주냉면     서울특별시 송파구 올림픽로12길 5-22 (잠실동)  424-7192
729     감베로니        서울특별시 용산구 한강대로81길 5 (갈월동)  3273-1791
730    장수설렁탕        서울특별시 송파구 백제고분로 148 (잠실동)  415-1472
731      무진장        서울특별시 용산구 원효로 212 (원효로2가)  712-8814

[732 rows x 3 columns]

In [ ]:
query = df5["업소 전화번호"]
added_query = []
for q in query:
    added_query.append(str(q)+'/')
len(added_query)

732

In [ ]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from tqdm import tqdm

In [ ]:
base_url = 'https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query='
rate = []
for i in tqdm(range(len(added_query))):
    try:
        url = base_url+added_query[i]    
        driver.get(url)
        time.sleep(0.3)
        a = driver.find_element(By.XPATH,'//*[@id="place-main-section-root"]/section/div/div[1]/div[1]/div[2]/span[1]/em')
        rate.append(a.text)
    except:
        rate.append("못찾았음")
    
rate

100%|██████████| 704/704 [09:38<00:00,  1.22it/s]

['4.34',
 '4.35',
 '4.42',
 '4.63',
 '못찾았음',
 '4.3',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.27',
 '못찾았음',
 '4.32',
 '못찾았음',
 '4.28',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.44',
 '못찾았음',
 '4.28',
 '못찾았음',
 '못찾았음',
 '4.2',
 '못찾았음',
 '4.47',
 '못찾았음',
 '못찾았음',
 '4.52',
 '4.51',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.26',
 '못찾았음',
 '3.98',
 '4.46',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.58',
 '4.3',
 '4.67',
 '못찾았음',
 '4.65',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.49',
 '4.32',
 '못찾았음',
 '4.31',
 '4.28',
 '못찾았음',
 '4.35',
 '4.31',
 '4.47',
 '4.42',
 '4.61',
 '4.07',
 '못찾았음',
 '4.39',
 '못찾았음',
 '4.2',
 '못찾았음',
 '4.35',
 '못찾았음',
 '4.54',
 '못찾았음',
 '4.28',
 '못찾았음',
 '못찾았음',
 '4.28',
 '4.08',
 '3.94',
 '4.32',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.55',
 '4.21',
 '못찾았음',
 '4.47',
 '4.33',
 '못찾았음',
 '4.01',
 '4.33',
 '4.53',
 '4.59',
 '못찾았음',
 '4.41',
 '못찾았음',
 '못찾았음',
 '4.12',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.1',
 '4.39',
 '못찾았음',
 '4.35',
 '4.12',
 '못찾았음',
 '못찾았음',
 '4.16',
 '4.27',
 '못찾았음',
 '4.25',
 '못찾았음',
 '못찾았음',
 '4.25',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.37',
 '4.4',
 '못찾았음',
 '못찾았음',
 '4.38',
 '못찾았음',
 '못찾았음',
 '4.19',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.48',
 '4.72',
 '4.27',
 '못찾았음',
 '못찾았음',
 '4.37',
 '4.26',
 '4.21',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.32',
 '못찾았음',
 '4.36',
 '4.38',
 '못찾았음',
 '4.45',
 '못찾았음',
 '4.5',
 '못찾았음',
 '4.47',
 '못찾았음',
 '4.21',
 '못찾았음',
 '4.12',
 '못찾았음',
 '4.22',
 '4.19',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.42',
 '못찾았음',
 '4.3',
 '못찾았음',
 '4.57',
 '4.46',
 '4.26',
 '4.27',
 '4.33',
 '4.3',
 '4.64',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.36',
 '4.19',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.27',
 '못찾았음',
 '4.56',
 '못찾았음',
 '못찾았음',
 '3.97',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.37',
 '4.36',
 '못찾았음',
 '4.08',
 '못찾았음',
 '4.47',
 '못찾았음',
 '못찾았음',
 '4.53',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.67',
 '4.27',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.23',
 '못찾았음',
 '4.21',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.41',
 '못찾았음',
 '3.85',
 '4.3',
 '못찾았음',
 '4.52',
 '4.54',
 '4.23',
 '못찾았음',
 '못찾았음',
 '4.25',
 '3.99',
 '4.28',
 '못찾았음',
 '4.45',
 '4.39',
 '4.36',
 '못찾았음',
 '못찾았음',
 '4.4',
 '못찾았음',
 '4.4',
 '4.33',
 '4.4',
 '못찾았음',
 '4.43',
 '4.45',
 '못찾았음',
 '4.44',
 '4.34',
 '3.5',
 '4.27',
 '4.7',
 '못찾았음',
 '4.39',
 '3.93',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.31',
 '4.34',
 '못찾았음',
 '4.5',
 '4.59',
 '못찾았음',
 '3.83',
 '4.48',
 '못찾았음',
 '4.4',
 '4.26',
 '못찾았음',
 '4.2',
 '못찾았음',
 '4.35',
 '못찾았음',
 '못찾았음',
 '4.28',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.24',
 '4.41',
 '4.29',
 '4.34',
 '4.4',
 '못찾았음',
 '못찾았음',
 '4.37',
 '4.55',
 '못찾았음',
 '4.43',
 '4.35',
 '4.24',
 '4.39',
 '4.41',
 '4.43',
 '못찾았음',
 '4.41',
 '4.53',
 '못찾았음',
 '못찾았음',
 '4.34',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.53',
 '못찾았음',
 '4.23',
 '못찾았음',
 '못찾았음',
 '4.19',
 '못찾았음',
 '4.41',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.25',
 '못찾았음',
 '4.54',
 '4.3',
 '4.18',
 '못찾았음',
 '4.26',
 '4.6',
 '못찾았음',
 '4.5',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.28',
 '못찾았음',
 '4.22',
 '4.4',
 '못찾았음',
 '4.15',
 '4.12',
 '4.35',
 '못찾았음',
 '4.05',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.27',
 '4.54',
 '4.37',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.3',
 '4.36',
 '못찾았음',
 '못찾았음',
 '4.37',
 '4.26',
 '못찾았음',
 '못찾았음',
 '4.83',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.15',
 '4.43',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.45',
 '4.36',
 '못찾았음',
 '못찾았음',
 '4.45',
 '4.42',
 '못찾았음',
 '3.79',
 '4.37',
 '4.13',
 '4.69',
 '4.25',
 '못찾았음',
 '못찾았음',
 '4.48',
 '4.36',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.38',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.27',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.43',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.37',
 '못찾았음',
 '못찾았음',
 '4.38',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.4',
 '3.56',
 '못찾았음',
 '4.31',
 '4.18',
 '못찾았음',
 '4.43',
 '4.29',
 '4.27',
 '못찾았음',
 '4.33',
 '4.23',
 '못찾았음',
 '4.09',
 '4.49',
 '못찾았음',
 '4.57',
 '못찾았음',
 '4.36',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.35',
 '4.42',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.48',
 '4.3',
 '4.24',
 '못찾았음',
 '못찾았음',
 '4.81',
 '4.28',
 '못찾았음',
 '4.28',
 '못찾았음',
 '못찾았음',
 '4.4',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.34',
 '못찾았음',
 '못찾았음',
 '4.56',
 '4.29',
 '못찾았음',
 '4.45',
 '못찾았음',
 '3.85',
 '못찾았음',
 '4.2',
 '못찾았음',
 '4.41',
 '못찾았음',
 '4.5',
 '4.43',
 '4.34',
 '못찾았음',
 '4.43',
 '못찾았음',
 '4.44',
 '못찾았음',
 '4.05',
 '4.29',
 '4.39',
 '4.05',
 '4.44',
 '못찾았음',
 '못찾았음',
 '4.14',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.51',
 '못찾았음',
 '4.29',
 '4.58',
 '4.22',
 '4.38',
 '4.24',
 '못찾았음',
 '4.33',
 '못찾았음',
 '4.11',
 '4.32',
 '4.32',
 '4.31',
 '못찾았음',
 '못찾았음',
 '4.41',
 '4.45',
 '4.54',
 '3.87',
 '못찾았음',
 '4.33',
 '4.04',
 '4.18',
 '4.53',
 '4.42',
 '4.13',
 '4.35',
 '4.21',
 '4.19',
 '못찾았음',
 '4.39',
 '4.48',
 '못찾았음',
 '4.38',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.09',
 '4.35',
 '4.46',
 '4.03',
 '못찾았음',
 '4.39',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.41',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.53',
 '4.54',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.29',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.41',
 '4.5',
 '4.35',
 '4.37',
 '못찾았음',
 '4.73',
 '4.57',
 '못찾았음',
 '못찾았음',
 '4.5',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.52',
 '4.28',
 '못찾았음',
 '못찾았음',
 '4.53',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.4',
 '4.51',
 '4.31',
 '못찾았음',
 '4.33',
 '못찾았음',
 '못찾았음',
 '4.55',
 '못찾았음',
 '4.16',
 '4.3',
 '4.63',
 '4.36',
 '4.22',
 '못찾았음',
 '4.37',
 '4.28',
 '4.38',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '3.82',
 '못찾았음',
 '못찾았음',
 '4.28',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.12',
 '4.22',
 '못찾았음',
 '4.24',
 '4.23',
 '못찾았음',
 '4.72',
 '4.4',
 '4.32',
 '못찾았음',
 '3.91',
 '4.41',
 '못찾았음',
 '4.54',
 '4.34',
 '3.95',
 '4.09',
 '4.26',
 '4.6',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.63',
 '못찾았음',
 '4.39',
 '못찾았음',
 '못찾았음',
 '4.15',
 '4.35',
 '4.1',
 '4.33',
 '4.48',
 '4.21',
 '4.35',
 '4.24',
 '못찾았음',
 '4.24',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.19',
 '4.22',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.05',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.33',
 '못찾았음',
 '못찾았음',
 '4.23',
 '4.24',
 '못찾았음',
 '4.34',
 '못찾았음',
 '못찾았음',
 '4.45',
 '못찾았음',
 '3.94',
 '못찾았음',
 '못찾았음',
 '4.25',
 '4.33',
 '4.23',
 '못찾았음',
 '4.38',
 '못찾았음',
 '4.44',
 '4.23',
 '못찾았음',
 '못찾았음',
 '못찾았음',
 '4.46',
 '못찾았음',
 '4.36',
 '못찾았음',
 '못찾았음',
 '3.99',
 '4.57',
 '못찾았음',
 '4.2']